# GAT Training Configuration
model:
  hidden_dim: 64
  num_layers: 3
  num_heads: 8
  dropout: 0.6
  negative_slope: 0.2
  add_self_loops: true

training:
  lr: 0.0005
  # L2 regularization coefficient
  weight_decay: 0.001
  # maximum number of training epochs
  epochs: 200

  # early stopping patience
  patience: 100
  min_delta: 0.0001

  batch_size: 1024

  # number of neighbors to sample (per layer)
  # [15, 10]表示第1层采样15个邻居，第2层采样10个邻居
  num_neighbors: [15, 10]
  # graph size threshold (use NeighborLoader sampling when node count exceeds this value)
  node_threshold: 2000
  train_ratio: 0.8
  num_workers: 0
  use_amp: false
  gradient_accumulation_steps: 1

  # Spatial smoothness regularization
  # Weight for smoothness loss (encourages neighboring buildings to have same class)
  lambda_smooth: 1.0  # Recommended range: 0.05-2.0 (start small)

  # Temperature for softmax in smoothness loss (lower = stricter constraint)
  smooth_temperature: 1.0

data:
  num_classes: 9
  district_ids: []
  normalize_features: true

logging:
  log_interval: 10
  checkpoint_interval: 50
  enable_tensorboard: true

seed: 42
